# HikariCP Configuration
jdbcUrl=jdbc:postgresql://localhost:5432/school_console_app
username=postgres
password=19
maximumPoolSize=10
minimumIdle=2
idleTimeout=60000
connectionTimeout=30000
autoCommit=true